name: edit values file in other repo

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest    

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Get updated values
      id: get-values
      run: echo "new_values=$(cat values.yaml)" >> "$GITHUB_OUTPUT"

    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: alexcamero/gh-actions-sandbox-2
        token: ${{ secrets.GH_TOKEN }}
      
    - name: write new value
      run: |-
          git config user.name alexcamero
          git config user.email alexcamero@gmail.com
          echo {{ steps.get-values.outputs.new_values }} > values.yaml
          git add values.yaml
          git commit -m "updating values file"
          git push
        
