name: edit values file in other repo

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest    

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # - name: Get updated values
    #   id: get-values
    #   run: |-
    #     echo "new_values<<EOF" >> $GITHUB_OUTPUT
    #     echo "$(cat values.yaml)" >> $GITHUB_OUTPUT
    #     echo "EOF" >> $GITHUB_OUTPUT

    - name: try git approach
      run: |-
        git config user.email "alexcamero@gmail.com"
        git config user.name "alexcamero"
        git clone --single-branch --branch main "https://${{ secrets.GH_TOKEN }}@github.com/alexcamero/gh-actions-sandbox-2.git" repo-2
        cp -rvf ./git-approach/ ./repo-2/git-approach/
        cd repo-2
        git add .
        git diff-index --quiet HEAD || git commit --message "files updated with git approach"
        git push origin


    # - name: Checkout
    #   uses: actions/checkout@v3
    #   with:
    #     repository: alexcamero/gh-actions-sandbox-2
    #     token: ${{ secrets.GH_TOKEN }}
      
    # - name: write new value
    #   run: |-
          
    #       echo "${{ steps.get-values.outputs.new_values }}" > values.yaml
    #       yq -i  '.latestSha = "${{ github.sha }}"' values.yaml
    #       git add values.yaml
    #       git commit -m "updating values file and latestSha --> $GITHUB_SHA"
    #       git push
        
