name: edit values file in other repo

on: [workflow_call]
  
jobs:
  build:
    runs-on: ubuntu-latest    

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # - name: Get updated values
    #   id: get-values
    #   run: |-
    #     echo "new_values<<EOF" >> $GITHUB_OUTPUT
    #     echo "$(cat values.yaml)" >> $GITHUB_OUTPUT
    #     echo "EOF" >> $GITHUB_OUTPUT

    - name: update repo 2
      run: |-
        git config --global user.email $EMAIL
        git config --global user.name $USER
        git clone --single-branch --branch main "https://$GH_PAT@github.com/alexcamero/gh-actions-sandbox-2.git" repo-2
        cp values.yaml repo-2/values.yaml
        cp -R git-approach/ repo-2
        cd repo-2
        yq -i  '.latestSha = "${{ github.sha }}"' values.yaml
        git add .
        git diff-index --quiet HEAD || git commit --message "update $GITHUB_SHA"
        git push origin


    # - name: Checkout
    #   uses: actions/checkout@v3
    #   with:
    #     repository: alexcamero/gh-actions-sandbox-2
    #     token: ${{ secrets.GH_TOKEN }}
      
    # - name: write new value
    #   run: |-
          
    #       echo "${{ steps.get-values.outputs.new_values }}" > values.yaml
    #       yq -i  '.latestSha = "${{ github.sha }}"' values.yaml
    #       git add values.yaml
    #       git commit -m "updating values file and latestSha --> $GITHUB_SHA"
    #       git push
        
