name: check for file changes against list of files
inputs:
  files:
    description: 'list of files to check for differences in'
    required: true

outputs:
  match-found:
    description: "boolean on whether any of the input files were changed"
    value: ${{ steps.match-check.outputs.match }}

runs:
  runs-on: ubuntu-latest

  steps:
  - name: Checkout
    uses: actions/checkout@v3
    with:
      fetch-depth: 2

  - name: check for match
    id: match-check
    env:
      FILES: ${{ input.files }}
    run: |-
      match=false
      for file in $(git diff --name-only HEAD^ HEAD | tr '\n' ' ')
      do
        for re in $FILES
        do
          if echo "$file" | grep -q -E "$re"; then
            echo "file matched: $file"
            match=true
            break
          fi
        done
        if [[ $match == true ]]; then
          break
        fi
      done
      echo "match=$match" >> "$GITHUB_OUTPUT"