name: general push

on:
  push:
    branches: [ main ]

jobs:
  get-diff:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: see list
      run: |-
        IFS=' ' read -ra changed_files <<< echo $(git diff --name-only HEAD^ HEAD)
        for file in "{changed_files[@]}"; do
          echo "$file"
        done

  # edit-values:
  #   uses: ./.github/workflows/edit-values.yaml