name: general push

on:
  push:
    branches: [ main ]

env:
  SPECIAL_FILES: "git-approach/* anotherfilehere"

jobs:
  get-diff:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: see list
      run: |-
        for file in $(git diff --name-only HEAD^ HEAD | tr '\n' ' ')
        do
          for re in $SPECIAL_FILES
          do
            if echo "$file" | grep -q -E "$re"; then
              echo "$file"
              done=yep
              break
            fi
          done
          if [[ $done == yep ]]; then
            break
          fi
        done

  # edit-values:
  #   uses: ./.github/workflows/edit-values.yaml