name: general push

on:
  push:
    branches: [ main ]

jobs:
  get-diff:
    uses: ./.github/workflows/file-diff.yaml

  first:
    needs: get-diff
    if: needs.get-diff.outputs.special
    uses: ./.github/workflows/this-first.yaml

  second:
    needs: get-diff
    if: needs.get-diff.outputs.extra-special
    uses: ./.github/workflows/this-second.yaml

  edit-values:
    if: ${{ always() }}
    needs: [first, second]
    uses: ./.github/workflows/edit-values.yaml