name: general push

on:
  push:
    branches: [ main ]

env:
  GH_PAT: ${{ secrets.GH_TOKEN }}
  GH_USER: "alexcamero"
  GH_EMAIL: "alexcamero@gmail.com"
  SPECIAL_FILES: ".github/workflows/* anotherfilehere"
  EXTRA_SPECIAL_FILES: "this_dir/*"

jobs:
  get-diff:
    runs-on: ubuntu-latest 
    outputs:
      special: ${{ steps.special.output.match-found }}
      extra-special: ${{ steps.extra-special.output.match-found }}

    steps:
    - name: check special matches
      id: special
      uses: ./.github/actions/file-diff.yaml
      with:
        files: $SPECIAL_FILES
    - name: check extra special matches
      id: extra-special
      uses: ./.github/actions/file-diff.yaml
      with:
        files: $EXTRA_SPECIAL_FILES

  first:
    needs: get-diff
    if: ${{ needs.get-diff.outputs.special }}
    uses: ./.github/workflows/this-first.yaml

  second:
    needs: get-diff
    if: ${{ needs.get-diff.outputs.extra-special }}
    uses: ./.github/workflows/this-second.yaml

  edit-values:
    runs-on: ubuntu-latest 
    if: ${{ always() }}
    needs: [get-diff, first, second]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: let's just take a look at these
      env:
        SPECIAL: ${{ needs.get-diff.outputs.special }}
        EXTRA_SPECIAL: ${{ needs.get-diff.outputs.extra-special }}
      run: |-
        echo $SPECIAL
        echo $EXTRA_SPECIAL

    - name: update repo-2
      run: |-
        git config --global user.email $GH_EMAIL
        git config --global user.name $GH_USER
        git clone --single-branch --branch main "https://$GH_PAT@github.com/alexcamero/gh-actions-sandbox-2.git" repo-2
        cp values.yaml repo-2/values.yaml
        cp -R git-approach/ repo-2
        cd repo-2
        yq -i  '.latestSha = "${{ github.sha }}"' values.yaml
        git add .
        git diff-index --quiet HEAD || git commit --message "update $GITHUB_SHA"
        git push origin