name: general push

on:
  push:
    branches: [ main ]

jobs:
  get-diff:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: git diff maybe
      run: echo $(git diff --name-only HEAD^ HEAD)

    - name: see the diff
      run: echo $(git diff-tree --no-commit-id --name-only -r HEAD)
  # edit-values:
  #   uses: ./.github/workflows/edit-values.yaml