name: general push

on:
  push:
    branches: [ main ]

jobs:
  get-diff:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      run: echo $(git diff-tree --no-commit-id --name-only -r HEAD)
  # edit-values:
  #   uses: ./.github/workflows/edit-values.yaml