name: check for file changes

on:
  workflow_call:
    inputs:
      tag-prefix:
        required: true
        type: string

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      TAG_PREFIX: ${{ inputs.tag-prefix }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get last tag that deployed
      run: |-
        git tag --sort=-taggerdate | tr -d " \t" | grep "^fancy-"
        git tag --sort=-taggerdate | tr -d " \t" | grep "^fancy-" | head -2 | tail -1