name: this one happens first

on: [workflow_call]

jobs:
  build-first:
    runs-on: ubuntu-latest    

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: and now do this extra special thing here
      run: echo "hey there extra special!"