name: this one happens first

on:
  push:
    branches: [ main ]

jobs:
  build-first:
    runs-on: ubuntu-latest    

    steps:
    - name: Checkout
      uses: actions/checkout@v3

  call-second:
    needs: [build-first]
    uses: ./.github/workflows/this-second.yaml