name: this one happens seond

on:
  workflow_run:
    workflows: [this one happens first]

jobs:
  build:
    runs-on: ubuntu-latest    

    steps:
    - name: Checkout
      uses: actions/checkout@v3