name: this one happens second

on: [workflow_call]

jobs:
  build-second:
    runs-on: ubuntu-latest    

    steps:
    - name: Checkout second
      uses: actions/checkout@v3

    -name: and now do this thing here